databases:
  - name: Subscriptions_API
    databaseName: subscriptions
    user: kidd

services:
  - type: web
    name: subscriptions_Web-API
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Subscriptions_API
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
